<?php
require_once __DIR__.'/bootstrap.php'; requireAdmin(); $pdo=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'){validateCsrf();$id=sanitizeInt($_POST['id']??0);$action=sanitizeString($_POST['action']??'status');
 if($action==='delete'){$s=$pdo->prepare('SELECT foto FROM alumni WHERE id=?');$s->execute([$id]);$a=$s->fetch();if($a){$pdo->prepare('DELETE FROM alumni WHERE id=?')->execute([$id]);$p=UPLOADS_PATH.'/alumni/'.basename($a['foto']);if(is_file($p))unlink($p);}setFlash('success','Data alumni dihapus.');}
 else{$status=sanitizeString($_POST['status']??'pending');$show=isset($_POST['tampil_landing'])?1:0;if(in_array($status,['pending','verified','rejected'],true)){$pdo->prepare('UPDATE alumni SET status=?, tampil_landing=? WHERE id=?')->execute([$status,$status==='verified'?$show:0,$id]);setFlash('success','Status dan tampilan alumni diperbarui.');}}
 redirect('/admin/alumni');}
$filter=sanitizeString($_GET['status']??'');$params=[];$sql='SELECT * FROM alumni';if(in_array($filter,['pending','verified','rejected'],true)){$sql.=' WHERE status=?';$params[]=$filter;}$sql.=' ORDER BY created_at DESC';$stmt=$pdo->prepare($sql);$stmt->execute($params);$items=$stmt->fetchAll();
$adminTitle='Data Alumni';$adminPage='admin/alumni';require __DIR__.'/includes/header.php';?>
<div class="admin-toolbar"><a class="btn-sm btn-sm-secondary" href="<?=BASE_URL?>/admin/alumni">Semua</a> <a class="btn-sm btn-sm-secondary" href="?status=pending">Pending</a> <a class="btn-sm btn-sm-secondary" href="?status=verified">Terverifikasi</a></div>
<div class="alumni-admin-grid"><?php foreach($items as $a):?><article class="admin-form-card alumni-admin-card"><img src="<?=e(BASE_URL.'/uploads/alumni/'.$a['foto'])?>" alt="<?=e($a['nama'])?>"><div><small>Lulus <?=e((string)$a['tahun_kelulusan'])?> · <?=e(ucfirst($a['aktivitas']))?> · <span class="badge <?=$a['orientasi']==='portrait'?'badge-green':'badge-blue'?>"><?=e($a['orientasi']??'landscape')?></span></small><h2><?=e($a['nama'])?></h2><p><?=e($a['alamat'])?></p><p><strong>Aktivitas:</strong> <?=e($a['aktivitas']==='kuliah'?$a['tempat_kuliah'].' — '.$a['jurusan']:$a['tempat_bekerja'].' — '.$a['jabatan'])?></p><p><strong>Pesan:</strong> <?=e($a['pesan_kesan'])?></p>
<form method="post" class="inline-status-form"><input type="hidden" name="csrf_token" value="<?=generateCsrfToken()?>"><input type="hidden" name="id" value="<?=$a['id']?>"><select class="form-control" name="status"><option value="pending" <?=$a['status']==='pending'?'selected':''?>>Pending</option><option value="verified" <?=$a['status']==='verified'?'selected':''?>>Diterima</option><option value="rejected" <?=$a['status']==='rejected'?'selected':''?>>Ditolak</option></select><label><input type="checkbox" name="tampil_landing" <?=$a['tampil_landing']?'checked':''?>> Landing</label><button class="btn-sm btn-sm-primary">Simpan</button><a class="btn-sm btn-sm-warning" href="<?=BASE_URL?>/admin/alumni-edit?id=<?=$a['id']?>">Edit</a></form>
<form method="post" onsubmit="return confirm('Hapus permanen data alumni ini?')" style="margin-top:8px"><input type="hidden" name="csrf_token" value="<?=generateCsrfToken()?>"><input type="hidden" name="id" value="<?=$a['id']?>"><input type="hidden" name="action" value="delete"><button class="btn-sm btn-sm-danger">Hapus</button></form></div></article><?php endforeach;?></div><?php if(!$items):?><div class="empty-state">Belum ada data alumni.</div><?php endif;?>
<?php require __DIR__.'/includes/footer.php';?>
