<?php
require_once __DIR__.'/bootstrap.php'; requireAdmin(); $pdo=getDB(); $errors=[];
if ($_SERVER['REQUEST_METHOD']==='POST') {
  validateCsrf(); $action=sanitizeString($_POST['action']??'upload');
  if($action==='delete'){ $id=sanitizeInt($_POST['id']??0);$s=$pdo->prepare('SELECT nama_file FROM dokumentasi WHERE id=?');$s->execute([$id]);$d=$s->fetch();if($d){$pdo->prepare('DELETE FROM dokumentasi WHERE id=?')->execute([$id]);$p=UPLOADS_PATH.'/dokumentasi/'.basename($d['nama_file']);if(is_file($p))unlink($p);}setFlash('success','Dokumentasi dihapus.');redirect('/admin/dokumentasi'); }
  $judul=sanitizeString($_POST['judul']??''); if($judul==='')$errors[]='Judul wajib diisi.';
  $map=['pdf'=>[['pdf'],['application/pdf'],20971520],'word'=>[['doc','docx'],['application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'],20971520],'video'=>[['mp4','webm'],['video/mp4','video/webm'],104857600],'foto'=>[['jpg','jpeg','png','webp'],['image/jpeg','image/png','image/webp'],10485760]];
  $ext=strtolower(pathinfo($_FILES['file']['name']??'',PATHINFO_EXTENSION));$tipe=match(true){$ext==='pdf'=>'pdf',in_array($ext,['doc','docx'],true)=>'word',in_array($ext,['mp4','webm'],true)=>'video',in_array($ext,['jpg','jpeg','png','webp'],true)=>'foto',default=>''};
  if(!$tipe)$errors[]='Format file tidak didukung.'; else $errors=array_merge($errors,validateUpload($_FILES['file'],$map[$tipe][0],$map[$tipe][1],$map[$tipe][2]));
  if(!$errors){$file=saveUpload($_FILES['file'],UPLOADS_PATH.'/dokumentasi');$mime=detectMimeType(UPLOADS_PATH.'/dokumentasi/'.$file);$pdo->prepare('INSERT INTO dokumentasi (judul,deskripsi,nama_file,nama_asli,tipe,mime_type,ukuran,is_published,uploaded_by) VALUES (?,?,?,?,?,?,?,?,?)')->execute([$judul,sanitizeString($_POST['deskripsi']??''),$file,basename($_FILES['file']['name']),$tipe,$mime,(int)$_FILES['file']['size'],isset($_POST['is_published'])?1:0,getCurrentUser()['id']]);setFlash('success','Dokumentasi berhasil diunggah.');redirect('/admin/dokumentasi');}
}
$items=$pdo->query('SELECT * FROM dokumentasi ORDER BY created_at DESC')->fetchAll();$adminTitle='Dokumentasi';$adminPage='admin/dokumentasi';require __DIR__.'/includes/header.php';?>
<div class="admin-form-card"><h2 class="admin-form-title">Upload Dokumentasi</h2><?php if($errors):?><div class="flash-message flash-error"><?=e(implode(' ',$errors))?></div><?php endif;?><form method="post" enctype="multipart/form-data" class="admin-form"><input type="hidden" name="csrf_token" value="<?=generateCsrfToken()?>"><div class="form-grid"><div class="form-group"><label>Judul *</label><input class="form-control" name="judul" required></div><div class="form-group"><label>File *</label><input class="form-control" type="file" name="file" accept=".pdf,.doc,.docx,.mp4,.webm,.jpg,.jpeg,.png,.webp" required></div></div><div class="form-group"><label>Deskripsi</label><textarea class="form-control" name="deskripsi"></textarea></div><label><input type="checkbox" name="is_published" checked> Tampilkan ke publik (Word tetap hanya tersimpan di admin)</label><div class="form-actions"><button class="btn-sm btn-sm-primary">Upload</button></div></form></div>
<div class="admin-table-card"><table class="admin-table"><thead><tr><th>Judul</th><th>Tipe</th><th>Ukuran</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($items as $d):?><tr><td><?=e($d['judul'])?></td><td><?=e(strtoupper($d['tipe']))?></td><td><?=e(formatBytes((int)$d['ukuran']))?></td><td><?=$d['is_published']?'Publik':'Privat'?></td><td><form method="post" onsubmit="return confirm('Hapus dokumentasi ini?')"><input type="hidden" name="csrf_token" value="<?=generateCsrfToken()?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$d['id']?>"><button class="btn-sm btn-sm-danger">Hapus</button></form></td></tr><?php endforeach;?></tbody></table></div>
<?php require __DIR__.'/includes/footer.php';?>
