<?php
if(empty($_SESSION['santri_id'])){setFlash('info','Silakan login dengan akun pendaftaran.');redirect('/login-santri');}
$pdo=getDB();$id=(int)$_SESSION['santri_id'];$errors=[];$settings=[];
$q=$pdo->query("SELECT key_name,value FROM pengaturan WHERE key_name IN ('biaya_penuh','biaya_ringan','biaya_beasiswa','rekening_pembayaran')");foreach($q->fetchAll() as $r)$settings[$r['key_name']]=$r['value'];
$s=$pdo->prepare('SELECT * FROM pendaftaran WHERE id=?');$s->execute([$id]);$p=$s->fetch();if(!$p){unset($_SESSION['santri_id']);redirect('/login-santri');}
if($_SERVER['REQUEST_METHOD']==='POST'){
 validateCsrf();$action=sanitizeString($_POST['action']??'');
 if($action==='biaya' && $p['status_pembayaran']!=='lunas'){$pilih=sanitizeString($_POST['pilihan_biaya']??'');if(in_array($pilih,['penuh','ringan','beasiswa'],true)){$nom=(float)($settings['biaya_'.$pilih]??0);$pdo->prepare('UPDATE pendaftaran SET pilihan_biaya=?,nominal_biaya=?,status_pembayaran=IF(status_pembayaran="ditolak","belum",status_pembayaran) WHERE id=?')->execute([$pilih,$nom,$id]);setFlash('success','Pilihan biaya disimpan. Silakan lakukan pembayaran dan upload buktinya.');redirect('/portal-santri');}}
 if($action==='upload_payment' && $p['status_pembayaran']!=='lunas'){
   if(!$p['pilihan_biaya'])$errors[]='Pilih skema biaya terlebih dahulu.';else{$up=validateUpload($_FILES['berkas'],['pdf','jpg','jpeg','png'],['application/pdf','image/jpeg','image/png'],10485760);if($up)$errors=array_merge($errors,$up);else{$file=saveUpload($_FILES['berkas'],UPLOADS_PATH.'/santri');$mime=(new finfo(FILEINFO_MIME_TYPE))->file(UPLOADS_PATH.'/santri/'.$file);$pdo->prepare("INSERT INTO berkas_santri (pendaftaran_id,jenis,nama_file,nama_asli,mime_type) VALUES (?,'bukti-bayar',?,?,?)")->execute([$id,$file,basename($_FILES['berkas']['name']),$mime]);$pdo->prepare("UPDATE pendaftaran SET status_pembayaran='menunggu' WHERE id=?")->execute([$id]);setFlash('success','Bukti pembayaran dikirim. Tunggu verifikasi admin sebelum melengkapi berkas.');redirect('/portal-santri');}}
 }
 if($action==='upload_document'){
   if($p['status_pembayaran']!=='lunas')$errors[]='Pemberkasan baru dibuka setelah pembayaran diverifikasi.';else{$jenis=sanitizeString($_POST['jenis']??'');$allowed=['kartu-keluarga','akta-lahir','ijazah','foto','lainnya'];if(!in_array($jenis,$allowed,true))$errors[]='Jenis berkas tidak valid.';else{$up=validateUpload($_FILES['berkas'],['pdf','jpg','jpeg','png'],['application/pdf','image/jpeg','image/png'],10485760);if($up)$errors=array_merge($errors,$up);else{$file=saveUpload($_FILES['berkas'],UPLOADS_PATH.'/santri');$mime=(new finfo(FILEINFO_MIME_TYPE))->file(UPLOADS_PATH.'/santri/'.$file);$pdo->prepare('INSERT INTO berkas_santri (pendaftaran_id,jenis,nama_file,nama_asli,mime_type) VALUES (?,?,?,?,?)')->execute([$id,$jenis,$file,basename($_FILES['berkas']['name']),$mime]);setFlash('success','Berkas berhasil diunggah.');redirect('/portal-santri');}}}
 }
}
$s=$pdo->prepare('SELECT * FROM pendaftaran WHERE id=?');$s->execute([$id]);$p=$s->fetch();$b=$pdo->prepare('SELECT * FROM berkas_santri WHERE pendaftaran_id=? ORDER BY created_at DESC');$b->execute([$id]);$files=$b->fetchAll();$paymentFiles=array_values(array_filter($files,fn($f)=>$f['jenis']==='bukti-bayar'));$documentFiles=array_values(array_filter($files,fn($f)=>$f['jenis']!=='bukti-bayar'));
$paymentLabels=['belum'=>'Belum dibayar','menunggu'=>'Menunggu verifikasi','lunas'=>'Pembayaran lunas','ditolak'=>'Bukti ditolak'];$activePage='psb';$pageTitle='Portal Santri | '.APP_NAME;$pageDescription='Pembayaran dan pemberkasan calon santri.';$pageCanonical=BASE_URL.'/portal-santri';?>
<main class="page-section portal-page"><div class="container"><div class="portal-head"><div><small><?=e($p['nomor_induk']?:$p['nomor_daftar'])?></small><h1>Assalamu’alaikum, <?=e($p['nama_lengkap'])?></h1><p>Status pembayaran: <strong><?=e($paymentLabels[$p['status_pembayaran']]??$p['status_pembayaran'])?></strong></p></div><a class="btn-outline" href="<?=BASE_URL?>/login-santri?logout=1">Keluar</a></div><?php if($errors):?><div class="flash-message flash-error"><?=e(implode(' ',$errors))?></div><?php endif;?>
<div class="portal-progress"><div class="progress-step active"><span>1</span><strong>Pendaftaran</strong></div><div class="progress-step <?=in_array($p['status_pembayaran'],['menunggu','lunas'])?'active':''?>"><span>2</span><strong>Pembayaran</strong></div><div class="progress-step <?=$p['status_pembayaran']==='lunas'?'active':''?>"><span>3</span><strong>Pemberkasan</strong></div></div>
<?php if($p['status_pembayaran']!=='lunas'):?><div class="portal-grid payment-stage"><section class="portal-card"><h2>1. Pilih Biaya Pendaftaran</h2><p>Pilih sesuai kemampuan keluarga. Jalur ringan dan beasiswa akan ditinjau pengurus.</p><form method="post"><input type="hidden" name="csrf_token" value="<?=generateCsrfToken()?>"><input type="hidden" name="action" value="biaya"><?php foreach(['penuh'=>'Biaya penuh','ringan'=>'Biaya ringan','beasiswa'=>'Jalur beasiswa'] as $v=>$label):?><label class="cost-option"><input type="radio" name="pilihan_biaya" value="<?=$v?>" <?=$p['pilihan_biaya']===$v?'checked':''?> required><span><strong><?=e($label)?></strong><small>Rp <?=number_format((float)($settings['biaya_'.$v]??0),0,',','.')?></small></span></label><?php endforeach;?><button class="btn-primary">Simpan Pilihan</button></form></section>
<section class="portal-card"><h2>2. Bayar &amp; Kirim Bukti</h2><div class="payment-info"><strong>Tujuan pembayaran</strong><p><?=nl2br(e($settings['rekening_pembayaran']??''))?></p></div><?php if($p['pilihan_biaya']):?><p>Nominal pilihan: <strong>Rp <?=number_format((float)$p['nominal_biaya'],0,',','.')?></strong></p><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=generateCsrfToken()?>"><input type="hidden" name="action" value="upload_payment"><div class="form-group"><label>Bukti pembayaran/pengajuan</label><input class="form-control" type="file" name="berkas" accept=".pdf,.jpg,.jpeg,.png" required></div><button class="btn-primary">Kirim Bukti Pembayaran</button></form><?php else:?><div class="payment-locked">Pilih skema biaya terlebih dahulu.</div><?php endif;?><ul class="portal-files"><?php foreach($paymentFiles as $f):?><li><span><?=e($f['nama_asli'])?></span><strong><?=e(ucfirst($f['status']))?></strong></li><?php endforeach;?></ul></section></div>
<div class="documents-locked"><strong>Pemberkasan belum dibuka</strong><p>Menu upload KK, akta, ijazah, dan pas foto akan terbuka otomatis setelah pembayaran diverifikasi admin.</p></div>
<?php else:?><div class="payment-success"><strong>✓ Pembayaran telah diverifikasi</strong><p>Silakan lanjutkan dengan melengkapi seluruh berkas yang dibutuhkan.</p></div><div class="portal-grid"><section class="portal-card"><h2>Lengkapi Berkas</h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=generateCsrfToken()?>"><input type="hidden" name="action" value="upload_document"><div class="form-group"><label>Jenis berkas</label><select class="form-control" name="jenis" required><option value="kartu-keluarga">Kartu Keluarga</option><option value="akta-lahir">Akta Lahir</option><option value="ijazah">Ijazah/SKL</option><option value="foto">Pas Foto</option><option value="lainnya">Lainnya</option></select></div><div class="form-group"><input class="form-control" type="file" name="berkas" accept=".pdf,.jpg,.jpeg,.png" required><small>Maksimal 10 MB.</small></div><button class="btn-primary">Upload Berkas</button></form><ul class="portal-files"><?php foreach($documentFiles as $f):?><li><span><?=e(ucwords(str_replace('-',' ',$f['jenis'])))?> — <?=e($f['nama_asli'])?></span><strong><?=e(ucfirst($f['status']))?></strong></li><?php endforeach;?></ul></section><section class="portal-card"><h2>Surat Kesanggupan</h2><p>Unduh, tandatangani bersama wali, lalu unggah kembali sebagai berkas lainnya.</p><a class="btn-primary" href="<?=BASE_URL?>/surat-kesanggupan">Download Surat Kesanggupan</a></section></div><?php endif;?></div></main>
